# Start by building the application.
FROM golang:1.13-buster as build

WORKDIR /go/src/app
ADD . /go/src/app

RUN go get -d -v ./...
#RUN go get github.com/thedevsaddam/renderer/...
RUN go get github.com/gorilla/mux
RUN go get github.com/nats-io/nats.go
RUN go get github.com/nats-io/stan.go

RUN go build -o /go/bin/app

# Now copy it into our base image.
FROM gcr.io/distroless/base-debian10
COPY --from=build /go/bin/app /
ADD . /
WORKDIR /
EXPOSE 8082
CMD ["/app"]